// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ratmon.Models;

#nullable disable

namespace Ratmon.Migrations
{
    [DbContext(typeof(RatmonDbContext))]
    [Migration("20250831114750_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Ratmon.Models.Mas2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<float>("Humidity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Mas2Set");
                });

            modelBuilder.Entity("Ratmon.Models.Mouse2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("Ω")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Mouse2Set");
                });

            modelBuilder.Entity("Ratmon.Models.Mouse2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("LeakLocation")
                        .HasColumnType("REAL");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("Ω")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Mouse2BSet");
                });

            modelBuilder.Entity("Ratmon.Models.Mouse2B_Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<double>("WireLength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Mouse2B_Config");
                });

            modelBuilder.Entity("Ratmon.Models.Mouse2_Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Mouse2_Config");
                });

            modelBuilder.Entity("Ratmon.Models.MouseCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("V")
                        .HasColumnType("REAL");

                    b.Property<double>("Ω")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MouseComboSet");
                });

            modelBuilder.Entity("Ratmon.Models.MouseCombo_Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Threshold")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MouseCombo_Config");
                });

            modelBuilder.Entity("Ratmon.Models.Reflectogram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("MouseComboId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("SeriesNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MouseComboId");

                    b.ToTable("Reflectogram");
                });

            modelBuilder.Entity("Ratmon.Models.Reflectogram", b =>
                {
                    b.HasOne("Ratmon.Models.MouseCombo", null)
                        .WithMany("Reflectograms")
                        .HasForeignKey("MouseComboId");
                });

            modelBuilder.Entity("Ratmon.Models.MouseCombo", b =>
                {
                    b.Navigation("Reflectograms");
                });
#pragma warning restore 612, 618
        }
    }
}
