@Ratmon_HostAddress = https://localhost:7119
@Ratmon_AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwianRpIjoiNzc5ZjVhMTYtYWM4NS00YzY4LWJkZmYtYzIwZWFkZTVjYTU1IiwibmFtZWlkIjoiYWI2MDhkNDMtMGRjZi00ZDE0LWI5MjYtYjdmYzMwYWZjNTEwIiwicm9sZSI6IkFkbWluIiwiTG9nZ2VkT24iOiIwMy4wOS4yMDI1IDIyOjQ2OjIyIiwibmJmIjoxNzU2OTMyMzgyLCJleHAiOjE3NTY5MzU5ODIsImlhdCI6MTc1NjkzMjM4MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdCJ9.XxYOl8wMFHaWnVGXJylsBEAyhqF8_tct6F8iDVwD6Fc


### Mouse2_Config Update
PUT {{Ratmon_HostAddress}}/settings/mouse2
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

{
    "name":"mouse2 12",
    "threshold": 50.57
}

### Mouse2B_Config Update
PUT {{Ratmon_HostAddress}}/settings/mouse2b
Content-Type: application/json

{
    "name":"mouse2b 34",
    "threshold": 50.57,
    "wireLength": 130
}

### Mouse2_Config Update
PUT {{Ratmon_HostAddress}}/settings/mousecombo
Content-Type: application/json

{
    "name":"mousecombo 56",
    "threshold": 60.75
}

### Mouse2_Config Update
PUT {{Ratmon_HostAddress}}/settings/mas2
Content-Type: application/json

{
    "name":"mas2 78",
    "temperaturethreshold": 10.15,
    "humiditythreshold": 30.2
}
