@Ratmon_HostAddress = https://localhost:7119
@Ratmon_AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb2huIiwianRpIjoiMjlkZjU2OGUtZGM5Ni00Y2UyLTg5NGEtYjQwZmQ2MjAzMWI3IiwibmFtZWlkIjoiYWI2MDhkNDMtMGRjZi00ZDE0LWI5MjYtYjdmYzMwYWZjNTEwIiwicm9sZSI6IkFkbWluIiwiTG9nZ2VkT24iOiIwMy4wOS4yMDI1IDIyOjQzOjEyIiwibmJmIjoxNzU2OTMyMTkyLCJleHAiOjE3NTY5MzU3OTIsImlhdCI6MTc1NjkzMjE5MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdCJ9.lUa4s0lNDarOf42AIw5cq01tcG6BEC_LbZXrvWEjla0


# GET {{Ratmon_HostAddress}}/mdata/
# Accept: application/json

### Mouse2 Get1
GET {{Ratmon_HostAddress}}/getdata/mouse2
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### Mouse2 Get2
GET {{Ratmon_HostAddress}}/getdata/mouse2?count=1
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### Mouse2B Get1
GET {{Ratmon_HostAddress}}/getdata/mouse2b
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### Mouse2B Get2
GET {{Ratmon_HostAddress}}/getdata/mouse2b?count=1
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### MouseCombo Get1
GET {{Ratmon_HostAddress}}/getdata/mousecombo
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### MouseCombo Get2
GET {{Ratmon_HostAddress}}/getdata/mousecombo?count=1
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### Mas2 Get1
GET {{Ratmon_HostAddress}}/getdata/mas2
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}

### Mas2 Get2
GET {{Ratmon_HostAddress}}/getdata/mas2?count=1
Content-Type: application/json
Authorization: Bearer {{Ratmon_AuthToken}}
